added map struct for external ids
rokwire/groups-building-block pull request #320
Opened 2022-12-19 17:30 UTC by bsdworkin

## Description
_Please provide a summary of the pull request and the issue it resolves. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._

Fix external ID handling

**Resolves #239**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] Immediately
- [ ] Within a week
- [ ] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

2022-12-21 11:11 UTC, mdryankov requested changes
I'm generally fine with this change, because it would open the platform for further external integrations. However supporting legacy  (keeping the legacy external_id) state is always a painful process which at some point produces problems in the near future. I would like to keep such support away as much as possible unless we have rock solid reason for the oposit.

@shurwit plrease feel free to add anything if I miss something.

2022-12-21 11:11 UTC, mdryankov commented on driven/storage/adapter.go
> +			externalIDs := map[string]string{"netID": current.NetID, "externalID": current.ExternalID}
Please use under scores instead of camel names. Camel names are not wrong approach. The idea is just to keep common standard within the project.

2022-12-21 11:11 UTC, mdryankov commented on driver/web/rest/apis.go
> +	externalIDs := map[string]string{"netID": current.NetID, "externalID": current.ExternalID}
Same as above/below

2022-12-21 11:11 UTC, mdryankov commented on driven/storage/adapter.go
> +			externalIDs := map[string]string{"netID": current.NetID, "externalID": current.ExternalID}
Also in this way of thoughts externalID is better to be renamed to uin, uiuc_uin if we gonna support more such attributes and external ids...

CC @shurwit

2025-08-05 13:17 UTC, mladen-inabyte commented
Closing this due to outdated changes.

2025-08-05 13:17 UTC, closed without merging