[ID-494]BBs Api for getting group memberships
rokwire/groups-building-block pull request #495
Opened 2024-08-15 20:49 UTC by stefanvit

## Description
BBs Api for getting group memberships

**Resolves #494 
## Review Time Estimate
- [ ] Immediately
- [ ] Within a week
- [x] When possible

## Type of changes
- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [x] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2024-08-15 20:51 UTC, stefanvit commented
Hi @petyos i've tested the API without permissions and i think it works fine. I want to ask you, should i use one of the other permission or should i make a new for this bbs API.

2024-08-19 03:48 UTC, petyos requested changes
Please take into account the feedback.

2024-08-19 03:48 UTC, petyos commented on driven/storage/database.go
> +	/*name := "title_unique"
Why was this commented?

2024-08-19 03:48 UTC, petyos commented on driver/web/rest/bbapis.go
> +// @Description  Gets all related group memberships status and group title using userID
Do not put the old way of docs approach.

2024-08-19 03:48 UTC, petyos commented on driven/storage/adapter_events.go
> +	groupMembership, err := sa.FindGroupMembershipsByUserID(userID)
Do not make two calles to the database but implement only one call using join.

2024-08-19 10:54 UTC, petyos approved these changes
LGTM

2024-08-19 11:37 UTC, merged